### ISSUE TITLE
Storage Space Cleaner has no function for cleaning

### ISSUE THREAD

**Issue by con-ssc** [deepakkumar1984/XrmToolBoxPlugins#1]
Currently, the plugin only displays the available old records. There is no functionality for actually cleaning those records. Also the close button is missing a correct label.

**Comment by deepakkumar1984** [comment]
Yes, you are right on the issue. I am currently working on it. 
Initially, I had the function to delete all records in a loop which was taking loads of time. Now I am planning to create bulk-delete job operation and wait for CRM to complete. Hopefully will be able to complete by this week.

**Comment by deepakkumar1984** [comment]
Fixed it and published the new version. Please take the update and let me know your feedback.
