### ISSUE TITLE
Feature request - User Audit Viewer - Export last logins for all users.

### ISSUE THREAD

**Issue by adner** [deepakkumar1984/XrmToolBoxPlugins#12]
Thanks for a great plugin!

It would be great if is was possible to export (to excel) a list of the last login for all users. Currently it is possible to select an individual user and export the login history for that user, but it would be nice if there was some way to export this information for all users at the same time.

**Comment by mprill** [comment]
This would be amazing for me as well, I have a number of users who have never logged in. Right now I'm having to click each one to see if there's an entry, if I could just export them all I'd be able to just sort it by date and remove everyone with no date. Thanks for this plugin Deepak!

**Comment by Niels-SL** [comment]
Yes. The ability to export all login transactions in a single Excel file would be a great addition.

**Comment by deepakkumar1984** [comment]
Loading the transaction history for all users takes a lot of time. I am not sure how useful it will be. I am planning to add the option anyway and see how it goes..

**Comment by mprill** [comment]
I would be happy as a clam to wait for it to load, it sure beats having to manually click through 1200 users to see if they've signed in.  

I'm hoping that since the plugin is already scanning to see if people logged in within the last 3/6 months it can just 1 tiny step further to show those who've never logged in, or just the last login for all users. 

Thanks so much!

**Comment by deepakkumar1984** [comment]
Did you try to see the Inactive users option, it will give to the users who are inactive from past 1/3/6 months?

**Comment by mprill** [comment]
Yes however it did not identify people who had never logged in last I checked.

**Comment by bartchambers** [comment]
I'd like to get a way to see logins for a timeframe. So I could look at the last 30 days and see who logged in each day. Then export that to a xls. Happy to make it worth your time. Thanks, Bart
