### ISSUE TITLE
KPI export

### ISSUE THREAD

**Issue by JanVanHaver** [deepakkumar1984/XrmToolBoxPlugins#15]
First & foremost: great tool - thx for making it available!

We're using your tool to get hold of some user adoption KPIs (of our D365 on-premises): by looking at the login history we check how many days it was since the most recent login (to see if people are actively using it at all), and in the transactions list we check the date of the oldest entry (which gives a rough idea of how actively the user is).

What would now make it even easier for us would be to be able to export 1 total list for all users, containing for each user the most recent date in Login History + the oldest date in Transactions + the offset (in days) from the date when the export is done.

I am not a prrogrammer, so no idea how realistic this request is - but I also did not want to leave it unmentioned in case it is relatively easy to accomplish.

**Comment by deepakkumar1984** [comment]
I would suggest use power BI for reporting
