### ISSUE TITLE
Recycle Bin Error when trying to retrieve a deleted case

### ISSUE THREAD

**Issue by Audwee66** [deepakkumar1984/XrmToolBoxPlugins#25]
I'm trying to recover a Case deleted in Dynamics 365 v 9.1 using Recycle Bin. I managed to recover the Contact for the Case, but when I try to recover the Case, I get the attached error. Can any one help? Don't want to have to restore a 240Gb database for one record!

![Recycle Bin Error](https://user-images.githubusercontent.com/53757158/62465014-db57ab80-b785-11e9-9bd0-70f761663bb2.png)

**Comment by Audwee66** [comment]
Apologies - here is the search result showing the Case record I want to recover.

![Recycle Bin Search Result](https://user-images.githubusercontent.com/53757158/62465383-aac44180-b786-11e9-8e5e-da263fdbc8c4.png)

**Comment by albertopb** [comment]
Hello,

I have the same issu. Did you fix it?

I deleted contacts in Dynamics with cases associated, after recover the contacts, i can't recover the cases... Anybody can help?

Thank you in advance

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
