### ISSUE TITLE
Restored Task, but "regarding" didn't come through.

### ISSUE THREAD

**Issue by vitsal** [deepakkumar1984/XrmToolBoxPlugins#27]
I've used this tool to restore tasks a while back, worked great. Today had to update xrmtoolbox and recyclebin to latest version and tried to restore a task, restore worked and task shows up in CRM but regarding is missing, possibly other associations, so what broke? I have a 3rd party app that looks up tasks, and regarding is required - so it's not showing up in my app. 

I can't remember which version i used when this worked, trying to dig that out...

**Comment by deepakkumar1984** [comment]
Which version  of CRM you are using?

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
