### ISSUE TITLE
Feature request: Cascading Restore

### ISSUE THREAD

**Issue by polshgiant** [deepakkumar1984/XrmToolBoxPlugins#3]
It would be awesome if the Recycle Bin tool provided the option to do a cascading restore.  So if I select a record to restore, maybe there's a separate Cascade Restore button which would inspect lookup values on the record being restored to see if they still exist.  If not, then the tool would check the audit history to see if the record in the lookup is also in the "recycle bin" and restore that record too.

**Comment by deepakkumar1984** [comment]
Not possible now. May be someone you know can take care of this
