### ISSUE TITLE
Not all fields are recovered

### ISSUE THREAD

**Issue by sim4sim** [deepakkumar1984/XrmToolBoxPlugins#30]
Hello, I have used the recycle bin yesterday to recover an Opportunity and unfortunately, some fields did not recover. Those fields included the Opportunity Name and a couple of mandatory fields. When I recovered an Account all fields came back through.

Is there a possibility that upon recovering an account all related entities would come back?

thank you!

**Comment by deepakkumar1984** [comment]
Which version of CRM you using?

**Comment by sim4sim** [comment]
we are on Dynamics 365 current version (2019)

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
