### ISSUE TITLE
Error message when trying to export inactive users

### ISSUE THREAD

**Issue by sjhaymore** [deepakkumar1984/XrmToolBoxPlugins#36]
Hi there,

I'm trying to export a list of inactive users with the User Audit Viewer plugin and am getting an error. I have used this plugin previously without issues but starting last week, I am unable to export the inactive users.

When I select any of the options in the drop-down for inactive users (1 Month, 3 Months, etc.), the message that the records are being retrieved pops up but then shortly after that an error pops up stating Object reference not set to an instance of an object.

I can see the login history for each individual user and it is only when I try to export using the Inactive users drop-down that the message appears. I've attached a screenshot of the error.

![XrmToolBox Error](https://user-images.githubusercontent.com/48104256/78042403-2b940700-732f-11ea-86c9-e32967ff9de2.PNG)

Our instance of MS Dynamics is on-premise for our vendor and in the cloud for us. Let me know if you need any additional information.

Thanks for any assistance you can provide.
Susan

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
