### ISSUE TITLE
Inactive users on xrm toolbox

### ISSUE THREAD

**Issue by JeroenTerpstra** [deepakkumar1984/XrmToolBoxPlugins#38]
Hi, 

when i try to see inactive users for the past 1 or 3 months i do not get any results.

also when i try to change the date for activity per user it won't show me any activities anymore.

Is there anything I am doing wrong, also  note that i only recently activated auditing on our Dynamics CRM environment. 

Thanks, 
Jeroen.

**Comment by deepakkumar1984** [comment]
Auditing is required for this to work. Probably thats  the reason.

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
