### ISSUE TITLE
Error Message when trying to restore something

### ISSUE THREAD

**Issue by stacyarambages** [deepakkumar1984/XrmToolBoxPlugins#39]
Hello.  I am getting a "contact with ID=   does not exist" error message and cannot restore my record.

![image](https://user-images.githubusercontent.com/68867358/88593279-4ea89c00-d02d-11ea-9356-dc93df697bd6.png)

---
- Deployment: Online
- DB Version: 9.1.0.19865
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2019.7.1

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
