### ISSUE TITLE
Timeout When Retrieving Inactive Users

### ISSUE THREAD

**Issue by corrivj** [deepakkumar1984/XrmToolBoxPlugins#40]
I'm getting timeouts when trying to retrieve inactive Users for 1, 2, 3 months.

![2020-08-11 14_49_55-Window](https://user-images.githubusercontent.com/41395023/89936761-1cc53700-dbe2-11ea-97d2-128e5a21f218.jpg)

Is there a way i can lookup not logged in x months for a subset of Users?  Can i just get an export of a view of Users and the date they Last Logged In?

Thanks,

Jim

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
