### ISSUE TITLE
.Net error when exporting list of inactive users to Excel (see screenshot)

### ISSUE THREAD

**Issue by Snappster55** [deepakkumar1984/XrmToolBoxPlugins#41]
Running XRM Toolbox version 1.2020.6.40 on Windows 10.

![image](https://user-images.githubusercontent.com/70540259/91769101-91f9ab80-eb93-11ea-8e52-4b13a0e76df4.png)

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
