### ISSUE TITLE
User Audit Viewer: Error when trying to save User Logins

### ISSUE THREAD

**Issue by olivermarshall2** [deepakkumar1984/XrmToolBoxPlugins#44]
[Write your comment/feedback/issue here]
[error.txt](https://github.com/tech-quantum/XrmToolBoxPlugins/files/5291238/error.txt)

If I "Click Export > Login History" in the User Audit Viewer I get a .Net error and the file doesn't get saved. Error file attached.

---
- Deployment: Online
- DB Version: 9.1.0.22849
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 2.2020.12.1

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that

**Comment by davem** [comment]
downloaded the latest version and getting an error when trying to export. as error as above

**Comment by deepakkumar1984** [comment]
I stopped supporting as this was free tool and I don’t have time and
energy. Please fork the repo and change the code as per your need

Regards,
Deepak
