### ISSUE TITLE
User login stats

### ISSUE THREAD

**Issue by olivermarshall2** [deepakkumar1984/XrmToolBoxPlugins#45]
Hi

Can I request a new feature? I use the user login toolbox to make sure users are logging in and using things as we move through our implementation of Dynamics. I'd love to see some stats, as well as the actual logins. So when you click on a users name, as well as the actual login events, I'd like to see Number of Logins in that date range.

It would also be great if you choose the number of logins shown on each page. I think currently it's 50 records, but sometimes it would be great to see all of them, or more than 50. 

Otherwise, great work. Thanks. 
---
- Deployment: Online
- DB Version: 9.1.0.23470
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 2.2020.12.1

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
