### ISSUE TITLE
Recycle Bin Exception Error on Certain Custom Entities But Not All Custom Entities

### ISSUE THREAD

**Issue by jsofer** [deepakkumar1984/XrmToolBoxPlugins#46]
The Recycle Bin plugin worked great for most of the entities I tried it on, but when I try it on a few specific custom entities, I get the following exception:

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Crm.Sdk.Messages.AuditDetail' to type 'Microsoft.Crm.Sdk.Messages.AttributeAuditDetail'.
   at BDK.XrmToolBox.RecycleBin.PluginControl.<btnShowRecords_Click>b__11_0(BackgroundWorker w, DoWorkEventArgs ev)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

I get it after choosing the entity, specifying a date range, and then clicking Show Deleted.  The recycle bin was working fine on these entities a few weeks ago so I'm not sure what has changed.  Could be some field in the entity or data elements?

Any ideas?

Thanks,
Jonathan

**Comment by camerontucker** [comment]
Looks like it just need a dependency bump. See #49

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
