### ISSUE TITLE
Recycle Bin

### ISSUE THREAD

**Issue by MariaG24** [deepakkumar1984/XrmToolBoxPlugins#47]
I've installed the Recycle Bin and it seems straightforward to used but, it's not showing any deleted data. I've been clean up for data storage this week so there should be some deleted records appearing.
Any suggestions?

Mgainsforth@remax.com

---
- Deployment: Online
- DB Version: 9.2.21051.140
- Connection Controls Version: 1.2021.6.43
- XrmToolBox Version: 1.2021.6.51
- Tool Version: 1.2019.7.1

**Comment by deepakkumar1984** [comment]
We need to auditing enabled. Please check the setting
