### ISSUE TITLE
Recycle bin doesn't recover deleted record

### ISSUE THREAD

**Issue by PeroPonneso** [deepakkumar1984/XrmToolBoxPlugins#54]
The plugin is not working.
It goes through all the phases without errors and prompt a successfull message about the recovered records 
![image](https://user-images.githubusercontent.com/77463786/159869984-9da64dc1-4c14-48d9-8220-fe1ab781a2ab.png)
even though the records are not being recovered

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
