### ISSUE TITLE
Idea for Restoring Child Items

### ISSUE THREAD

**Issue by donalmc** [deepakkumar1984/XrmToolBoxPlugins#56]
When you delete an item with child items, these items are also deleted.
If you try to restore the children after restoring the parent, you get an error message about 'record with Id = guid.... Does Not Exist' - this is understandable as the restored parent now has a new GUID.
Would it be possible for the 'does not exist' dialog to include an 'Alternative GUID' text field?
We could go grab the GUID from the restored parent and enter it here.

**Comment by deepakkumar1984** [comment]
I don't have time to expand the tool. Sorry
