### ISSUE TITLE
Restoring appointments issue

### ISSUE THREAD

**Issue by ersatzDev** [deepakkumar1984/XrmToolBoxPlugins#7]
Hi, 
I'm trying to restore some deleted appointments but I'm getting this error: 

5 is not a valid status code for state code AppointmentState.Open on appointment with Id bb6e7324-400f-e711-8105-005056960cac.

Looks like needs a tweak on the restore operation so it sets the status reason to one of the proper ones for the open state. 

Here you can check the available Status Reason for State = "OPEN"  for the appointment entity https://technet.microsoft.com/en-us/library/dn531157.aspx

**Comment by deepakkumar1984** [comment]
Same as Issue : https://github.com/deepakkumar1984/XrmToolBoxPlugins/issues/5
