### ISSUE TITLE
Value of Partial URL field of the Home Page of your website can only be /. Any other values will lead to issues in your Portal.

### ISSUE THREAD

**Issue by L-PDS** [deepakkumar1984/XrmToolBoxPlugins#71]
I'm trying to use the tool to restore an accidentally deleted "Access-denied" web page. The web page Partial URL is access-denied. I get the error:

"Value of Partial URL field of the Home Page of your website can only be /. Any other values will lead to issues in your Portal."

The home page does have a / partial url, and I'm not trying to restore the home page.

**Comment by deepakkumar1984** [comment]
Released a new update, can you please try in that
